apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      imagePullSecrets:
        - name: ghcr-registry
      containers:
      - name: frontend
        image: ghcr.io/contextualwisdomlab/ai_email_client-frontend:REPLACE_ME_VERSION
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 1000
          runAsNonRoot: true
          runAsUser: 1000
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: frontend-next-cache
          mountPath: /app/.next/cache
        - name: frontend-tmp
          mountPath: /tmp
        env:
          - name: BACKEND_INTERNAL_URL
            value: "http://backend:8000"
          - name: ALLOW_DOCKER_BACKEND_INTERNAL_URL
            value: "1"
      volumes:
      - name: frontend-next-cache
        emptyDir: {}
      - name: frontend-tmp
        emptyDir: {}
